version: '3.9'

services:
  rest-api:
    build: 
      context: .
      dockerfile: Dockerfile
    image: rest-api
    container_name: rest-taller-views 
    ports:
      - 8000:8000
    expose:
      - 8000
    volumes:
      - .:/app/
    command: python manage.py runserver 0.0.0.0:8000
  
networks:
  default:
    name: development
    external: true